//TS_BUFFER
#define FRAME_LEN 188
#define TS_BUFFER_CTL_LEN 100
#define TS_BUFFER_MAX_LEN FRAME_LEN*1000000+TS_BUFFER_CTL_LEN
#define TS_BUFFER_WRITER_OFFS 0
#define TS_BUFFER_READER_OFFS 4
#define TS_BUFFER_ORI_RATE_OFFS 8
#define TS_BUFFER_WRITER_AV_OFFS 16


